language: node_js
node_js: node
deploy: https://young-reaches-75979.herokuapp.com
  provider: heroku
  api_key:
    secure: iFQF4lk+zJ9be9QHUFJIf6G82f7WxO06zjtX1Fgi0DzsS2tbr6tVwtwDWNo+RayVQPXYyGorGWT+d5NdLUyybU2938B31Mp3i23ZUetFBm+6b75lZsQ49fh3spJjQV7jR5yr5o9DURNg8aVDfwO/7t41XpBgBVPsD4LUv48GtChMoY3M5BAPRD2gwtAHyqvO1KZIxIZxp9PR2dHpuuCt36uOrWoOvt3hv0tiEtR9sd3BXnhUJ802ofSsSvNqQ5pKtahQVRryHTETPtzdz2cnok17rZ0Ddx23s24eMxEydSn+GvlaLRjydfQGng3Hp+dQR7VOSHZSw9ewgsOb+w+yKI/dVC7VL63CIOOiAJxVTlKAePXEhtQEPF6UBgkvzKCmKKo4ctnZN/HzQJ7SvD8SSB1f3oVlyE0s+AmMOp8LqD9bYypTpYF9Ebz4Q8lL5OfugEbSi0cFE9dYzmhrL6Eu1/6fXh/orbwZGl5Hyy5Q30k8F5j9yR9GrbEtqN78hLpB3Df9UugUpRaC3psOEoGUtjFnigMKCp3+nuyPqhW7n1E4YgusJ9qXtMAMIofrNxF+4iVkkFSMe2/nHUwCoO5iE72IigEsd87JfFxqE2lmPYhzbi0JI/iKBGPXJUyRLGwKGdLzhQM0jXqHcBC7iN+UAbgLi5Onl5YvSHRXryiNTa8=
  app: node-shopping-list-integration-tests
  on:
    repo: Korneliu/node-shopping-list-integration-tests
